version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: recupera-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recupera-network

  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: recupera-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      SPRINGDOC_SWAGGER_UI_PATH: ${SPRINGDOC_SWAGGER_UI_PATH}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - recupera-network

volumes:
  postgres_data:

networks:
  recupera-network:
    driver: bridge