FROM maven:3.6.3-openjdk-17 as build
WORKDIR /usr/src/app
COPY recupera/ .
RUN mvn package -DskipTests

FROM openjdk:17-slim
RUN apt-get update && apt-get install -y netcat-openbsd
COPY --from=build /usr/src/app/target/recupera-0.0.1-SNAPSHOT.jar /app/app.jar
COPY recupera/wait-for-it.sh /app/wait-for-it.sh
RUN chmod +x /app/wait-for-it.sh
EXPOSE 8080
CMD ["sh", "-c", "/app/wait-for-it.sh $(echo $SPRING_DATASOURCE_URL | sed 's/jdbc:postgresql:\\/\\///;s/\\/.*//') -- java -jar /app/app.jar"]
